version: "2"
networks:
  dmc:
    external: true
volumes:
  etc:
    external: true
  lib:
    external: true
  #var:
  #  external: true
services:
  #local-arangodb:
  #  build:
  #    context: ./service/arangodb
  #  image: dmc:arangodb
  local-node:
    build:
      context: ./service/node
    environment:
      GURUMOJO_ENVIRONMENT: development
      GURUMOJO_REDIS_EXPOSE: 6379
      GURUMOJO_REDIS_HOSTNAME: dmc_redis_1
    extends:
      file: docker-service.yml
      service: base
    image: dmc:node
  #local-rabbitmq:
  #  build:
  #    context: ./service/rabbitmq
  #  image: dmc:rabbitmq
  local-redis:
    build:
      context: ./service/redis
    image: dmc:redis
    networks:
      - dmc
