version: "2"
networks:
  gurumojo:
    external: true
volumes:
  etc:
    external: true
  lib:
    external: true
  #var:
  #  external: true
services:
  local-node:
    build:
      context: ./service/node
    image: gurumojo:node
  local-redis:
    build:
      context: ./service/redis
    image: gurumojo:redis
  development:
    build:
      context: ./service/base
    extends:
      file: docker-service.yml
      service: base
    environment:
      GURUMOJO_ENVIRONMENT: development
      GURUMOJO_REDIS_EXPOSE: 6379
      GURUMOJO_REDIS_HOSTNAME: dmc_redis_1
    image: gurumojo:development
