version: "2"
networks:
  dmc:
    external: true
volumes:
  etc:
    external: true
  lib:
    external: true
  #var:
  #  external: true
services:
  #arangodb:
  #  expose:
  #    - 8529
  #  image: arangodb:alpine
  #  networks:
  #    - dmc
  #  volumes:
  #    - ./var/arangodb:/var/lib/arangodb3
  #rabbitmq:
  #  expose:
  #    - 15672
  #  image: rabbitmq:alpine
  #  networks:
  #    - dmc
  #  volumes:
  #    - ./var/rabbitmq:/var/lib/rabbitmq
  redis:
    extends:
      file: docker-environment.yml
      service: local-redis
    volumes:
      - ./var/redis:/data
  example:
    build:
      context: ./opt/example
    extends:
      file: docker-environment.yml
      service: local-node
    image: example:development
    ports:
      - 8000:80
    volumes:
      - ./opt/example:/opt/dmc
