version: "2"
networks:
  gurumojo:
    external: true
volumes:
  etc:
    external: true
  lib:
    external: true
  #var:
  #  external: true
services:
  #arangodb:
  #  expose:
  #    - 8529
  #  image: arangodb:alpine
  #  networks:
  #    - gurumojo
  #  volumes:
  #    - ./var/arangodb:/var/lib/arangodb3
  #rabbitmq:
  #  expose:
  #    - 15672
  #  image: rabbitmq:alpine
  #  networks:
  #    - gurumojo
  #  volumes:
  #    - ./var/rabbitmq:/var/lib/rabbitmq
  redis:
    expose:
      - 6379
    image: gurumojo:redis
    networks:
      - gurumojo
    volumes:
      - ./var/redis:/data
  #template:
  #  build:
  #    context: ./service/template
  #  depends_on:
  #    - redis
  #  extends:
  #    file: docker-environment.yml
  #    service: development
  #  image: template:development
  #  ports:
  #    - 7000:80
  #  volumes:
  #    - ./service/template:/opt/gurumojo
  example:
    build:
      context: ./service/example
    extends:
      file: docker-environment.yml
      service: development
    image: example:development
    ports:
      - 8000:80
    volumes:
      - ./service/example:/opt/gurumojo
