version: "2"
networks:
  dmc:
    external: true
volumes:
  etc:
    external: true
  lib:
    external: true
  #var:
  #  external: true
services:
  #local-arangodb:
  #  build:
  #    context: ../../opt/arangodb
  #  image: dmc:arangodb
  local-node:
    build:
      context: ../../opt/node
    environment:
      DMC_ENVIRONMENT: development
      DMC_REDIS_PORT: 6379
      DMC_REDIS_HOST: docker_redis_1
    extends:
      file: service.yml
      service: base
    image: dmc:node
  #local-rabbitmq:
  #  build:
  #    context: ../../opt/rabbitmq
  #  image: dmc:rabbitmq
  local-redis:
    build:
      context: ../../opt/redis
    image: dmc:redis
    networks:
      - dmc
